/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl;

import org.xtext.example.htmldsl.AbstractHtmlDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class HtmlDslRuntimeModule extends AbstractHtmlDslRuntimeModule {
}
