/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl;

import org.xtext.example.htmldsl.HtmlDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class HtmlDslStandaloneSetup extends HtmlDslStandaloneSetupGenerated {
  public static void doSetup() {
    HtmlDslStandaloneSetup _htmlDslStandaloneSetup = new HtmlDslStandaloneSetup();
    _htmlDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
