/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.htmldsl.ui.AbstractHtmlDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class HtmlDslUiModule extends AbstractHtmlDslUiModule {
  public HtmlDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
