/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HtmlDslStandaloneSetup extends HtmlDslStandaloneSetupGenerated {

	def static void doSetup() {
		new HtmlDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
