@startuml
hide circle
hide empty methods
scale 3840*2160

abstract class Class {
    name: String
    selector: Selector
}

abstract class ClassificationModel {
    classes: List<Class>
}

class ContentClass {
    selector: ContentSelector
}

abstract class FeatureClass {
    selector: FeatureSelector
}

abstract class FeatureCapableClass {
    features: List<Feature>
}

class PageClass {
    selector: PageSelector
}

class ReferenceClass {
    selector: ReferenceSelector
}

abstract class Selector
abstract class Feature

Class <|-- FeatureClass
Class <|-- FeatureCapableClass
Class "0..1" -- "0..1" Selector : > hat
ClassificationModel "1" -- "0..n" Class : > enthält
FeatureCapableClass <|-- ContentClass
FeatureCapableClass "1" -- "0..n" Feature : > hat
FeatureCapableClass <|-- PageClass
FeatureClass <|-- ContentClass
FeatureClass <|-- ReferenceClass
@enduml