@startuml
hide circle
hide empty methods
scale 3.25
skinparam linetype ortho

abstract class Class {
    name: String
    selector: Selector
}

class ClassificationModel {
    classes: List<Class>
}

class ContentClass<T extends ContentSelector> {
    selector: T
}

abstract class FeatureClass<T extends FeatureSelector> {
    selector: T
}

abstract class FeatureCapableClass {
    features: List<Feature>
}

class PageClass {
    selector: PageSelector
}

class ReferenceClass<T extends ReferenceSelector> {
    selector: T
}

abstract class Selector
class Feature

Class <|-- FeatureClass
Class <|-- FeatureCapableClass
Class "1" --> "0..1" Selector : > specifies
ClassificationModel "1" --> "0..n" Class : > contains
FeatureCapableClass <|-- ContentClass
FeatureCapableClass "1" --> "0..n" Feature : > declares
FeatureCapableClass <|-- PageClass
FeatureClass <|-- ContentClass
FeatureClass <|-- ReferenceClass
@enduml