@startuml
hide circle
hide empty methods
scale 3.25
left to right direction
skinparam linetype ortho

class Feature<T extends FeatureSelector> {
    name: String
    class: FeatureClass<T>
    selector: T
    isCollectionFeature: Boolean
}

abstract class FeatureClass<T extends FeatureSelector>
abstract class FeatureSelector

Feature "0..n" --> "1" FeatureClass : > is of class
Feature "0..n" --> "0..1" FeatureSelector : > specifies
@enduml