@startuml
hide circle
hide empty methods
scale 3.25

class CollectionFeature
abstract class Feature {
    name: String
    class: FeatureClass
    selector: FeatureSelector
}
class ScalarFeature

abstract class FeatureClass
abstract class FeatureSelector

Feature <|-- CollectionFeature
Feature "0..n" -- "1" FeatureClass : > hat
Feature "0..n" -- "0..1" FeatureSelector : > hat
Feature <|-- ScalarFeature
@enduml