@startuml
hide circle
hide empty methods
left to right direction
scale 3840*2160

abstract class ContentSelector
class CssSelector
abstract class FeatureSelector
abstract class PageSelector
abstract class ReferenceSelector
abstract class Selector {
    value: String
}
class UrlPatternSelector
class XPathSelector

ContentSelector <|-- CssSelector
ContentSelector <|-- XPathSelector
FeatureSelector <|-- ContentSelector
FeatureSelector <|-- ReferenceSelector

PageSelector <|-- UrlPatternSelector
ReferenceSelector <|-- CssSelector
ReferenceSelector <|-- UrlPatternSelector
ReferenceSelector <|-- XPathSelector

Selector <|-- PageSelector
Selector <|-- FeatureSelector
@enduml