package Kaja.sandbox.sandbox;

/*Generated by MPS */

import JavaKaja.runtime.KajaFrame;
import JavaKaja.runtime.Direction;

public class DiagonalMovement extends KajaFrame {
  public DiagonalMovement() {
  }
  protected void perform() {
    if (isAllowedRow(5) && isAllowedCol(6)) {
      if (!(isFull(5, 6))) {
        addMark(5, 6);
        minipause();
      } else {
        reportError("Cannot drop. The cell is already full.");
        return;
      }
    } else {
      reportError("Attempted to drop marks outside of the playground!");
    }
    while (!(heading(Direction.south))) {
      turnLeft();
      pause();
    }
    while (!(isWall())) {
      if (canMove()) {
        moveKaja();
        pause();
      } else {
        reportError("Oops, There's a wall in front of me. I can't make a step forward.");
      }
    }
    turnLeft();
    pause();
    turnHalfLeft();
    pause();
    while (!(isMark())) {
      if (canMove()) {
        moveKaja();
        pause();
      } else {
        reportError("Oops, There's a wall in front of me. I can't make a step forward.");
      }
    }
  }
  public static void main(String[] args) {
    DiagonalMovement script = new DiagonalMovement();
    script.initializeComponents();
    script.run();
  }
}
