@startuml
scale 3.25
skinparam componentStyle uml2

actor "WCCS Power User" as Admin
actor "WCCS User" as Reviewer

' External Components
[WordPress] <<external component>> as wordpress
[Web Page] <<external component>> as web_page

' WCCS Components
[Annotator Plugin] <<WCCS component>> as annotator_plugin
[Classification Service] <<WCCS component>> as classification_service
[WordPress Crawler] <<WCCS component>> as wp_crawler

Admin --> wp_crawler : runs classification through
'Beziehung zwischen Annotator Plugin und Classification Service bewusst weggelassen
classification_service --> web_page : classifies
Reviewer --> web_page : reviews classification through
Reviewer --> annotator_plugin
web_page --> wordpress : shows content from
web_page -(0- annotator_plugin : includes
wp_crawler -(0- classification_service : calls
wp_crawler --> web_page : discovers
wp_crawler -(0- wordpress : implements discovery through
@enduml