@startuml
scale 3840*2160
skinparam componentStyle uml2

actor Admin

[Annotator Plugin] <<component>> as annotator_plugin
[Annotation Service] <<component>> as annotation_service
[Class Definition Language] <<component>> as dsl
[Classification Service] <<component>> as classification_service
[Classification Storage API] <<component>> as classification_storage_api
[Classification Storage] <<component>> as classification_storage
[Web App] <<component>> as web_app

Admin --> web_app : Prüft Klassifikation mit
Admin --> dsl : Konfiguriert Klassifizierung mit
annotation_service -(0- classification_storage_api
annotator_plugin -(0- annotation_service : Integriert WCCS in Annotator
classification_service -(0- classification_storage_api
classification_storage_api -(0- classification_storage
dsl --> classification_service : Erzeugt Konfiguration für
web_app -(0- classification_storage_api
@enduml