@startuml
scale 3.25
skinparam componentStyle uml2

actor "WCCS Power User" as Admin
actor "Third Party System" as classification_processing_system

[Annotator Plugin] <<component>> as annotator_plugin
[Annotation Service] <<component>> as annotation_service
[Class Definition Language] <<component>> as dsl
[Classification Service] <<component>> as classification_service
[Classification Storage API] <<component>> as classification_storage_api
[Classification Storage] <<component>> as classification_storage
[Web App] <<component>> as web_app

Admin --> web_app : examines classification with
Admin --> dsl : creates classification model with
annotation_service -(0- classification_storage_api : reads and writes classification through
annotator_plugin -(0- annotation_service : integrates WCCS in Annotator through
annotator_plugin -(0- classification_service : reads classification model from
classification_service -(0- classification_storage_api : writes classification through
classification_storage_api -(0- classification_storage : stores classifications in
classification_storage_api -0)- classification_processing_system  : accesses classification through
dsl --> classification_service : generates configuration for
web_app -(0- classification_storage_api : reads classification through
@enduml