@startuml
!include c5.plantuml
!include r2.plantuml

scale 3.25
hide circle
hide empty methods
left to right direction

object "rel10 : ReferenceRelationship" as rel10 {
    class = "InternalLink"
    name = "internalLinks"
    isCollection = true
    selectorType = "RangeSelector"
    startSelectorType = "XPathSelector"
    startSelectorValue = "/html/body/[...]/a"
    startSelectorOffset = 0
    endSelectorType = "XPathSelector"
    endSelectorValue = "/html/body/[...]/a"
    endSelectorOffset = 25
}

generalInformationContent --> otherPage : Owns
(generalInformationContent, otherPage) .. rel10
@enduml