@startuml
!include c5.plantuml
!include r1.plantuml
!include r2.plantuml

scale 3.25
left to right direction

generalInformationContent --> image : rel9 : References
generalInformationContent --> otherPage : rel10 : References
@enduml