@startuml
!include content-owner-relationships.plantuml
!include resource-referencer-relationships.plantuml
!include Content.plantuml
!include Page.plantuml
!include Resource.plantuml

scale 3.25
left to right direction
hide circle
hide empty methods

class Site {
    id : String
}

class Text {
    value : String
}

Content "1..n" --> "0..1" Text : > reads
Site "1" --> "0..n" Page : > owns
@enduml