/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl.htmlDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Anchor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.htmldsl.htmlDsl.Anchor#getDestination <em>Destination</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.htmldsl.htmlDsl.HtmlDslPackage#getAnchor()
 * @model
 * @generated
 */
public interface Anchor extends BodyElement
{
  /**
   * Returns the value of the '<em><b>Destination</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Destination</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destination</em>' reference.
   * @see #setDestination(Page)
   * @see org.xtext.example.htmldsl.htmlDsl.HtmlDslPackage#getAnchor_Destination()
   * @model
   * @generated
   */
  Page getDestination();

  /**
   * Sets the value of the '{@link org.xtext.example.htmldsl.htmlDsl.Anchor#getDestination <em>Destination</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Destination</em>' reference.
   * @see #getDestination()
   * @generated
   */
  void setDestination(Page value);

} // Anchor
