/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl.htmlDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Body Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.htmldsl.htmlDsl.HtmlDslPackage#getBodyElement()
 * @model
 * @generated
 */
public interface BodyElement extends EObject
{
} // BodyElement
