/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl.htmlDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Page</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.htmldsl.htmlDsl.Page#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.htmldsl.htmlDsl.Page#getBodyElements <em>Body Elements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.htmldsl.htmlDsl.HtmlDslPackage#getPage()
 * @model
 * @generated
 */
public interface Page extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.htmldsl.htmlDsl.HtmlDslPackage#getPage_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.htmldsl.htmlDsl.Page#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Body Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.htmldsl.htmlDsl.BodyElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body Elements</em>' containment reference list.
   * @see org.xtext.example.htmldsl.htmlDsl.HtmlDslPackage#getPage_BodyElements()
   * @model containment="true"
   * @generated
   */
  EList<BodyElement> getBodyElements();

} // Page
