/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl.htmlDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Web Site</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.htmldsl.htmlDsl.WebSite#getPages <em>Pages</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.htmldsl.htmlDsl.HtmlDslPackage#getWebSite()
 * @model
 * @generated
 */
public interface WebSite extends EObject
{
  /**
   * Returns the value of the '<em><b>Pages</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.htmldsl.htmlDsl.Page}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pages</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pages</em>' containment reference list.
   * @see org.xtext.example.htmldsl.htmlDsl.HtmlDslPackage#getWebSite_Pages()
   * @model containment="true"
   * @generated
   */
  EList<Page> getPages();

} // WebSite
