/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl.htmlDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.htmldsl.htmlDsl.BodyElement;
import org.xtext.example.htmldsl.htmlDsl.HtmlDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Body Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BodyElementImpl extends MinimalEObjectImpl.Container implements BodyElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BodyElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HtmlDslPackage.Literals.BODY_ELEMENT;
  }

} //BodyElementImpl
