/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl.htmlDsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.htmldsl.htmlDsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class HtmlDslFactoryImpl extends EFactoryImpl implements HtmlDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static HtmlDslFactory init()
  {
    try
    {
      HtmlDslFactory theHtmlDslFactory = (HtmlDslFactory)EPackage.Registry.INSTANCE.getEFactory(HtmlDslPackage.eNS_URI);
      if (theHtmlDslFactory != null)
      {
        return theHtmlDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new HtmlDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HtmlDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case HtmlDslPackage.WEB_SITE: return createWebSite();
      case HtmlDslPackage.PAGE: return createPage();
      case HtmlDslPackage.BODY_ELEMENT: return createBodyElement();
      case HtmlDslPackage.HEADING1: return createHeading1();
      case HtmlDslPackage.HEADING2: return createHeading2();
      case HtmlDslPackage.PARAGRAPH: return createParagraph();
      case HtmlDslPackage.ANCHOR: return createAnchor();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WebSite createWebSite()
  {
    WebSiteImpl webSite = new WebSiteImpl();
    return webSite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Page createPage()
  {
    PageImpl page = new PageImpl();
    return page;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BodyElement createBodyElement()
  {
    BodyElementImpl bodyElement = new BodyElementImpl();
    return bodyElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Heading1 createHeading1()
  {
    Heading1Impl heading1 = new Heading1Impl();
    return heading1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Heading2 createHeading2()
  {
    Heading2Impl heading2 = new Heading2Impl();
    return heading2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Paragraph createParagraph()
  {
    ParagraphImpl paragraph = new ParagraphImpl();
    return paragraph;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Anchor createAnchor()
  {
    AnchorImpl anchor = new AnchorImpl();
    return anchor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HtmlDslPackage getHtmlDslPackage()
  {
    return (HtmlDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static HtmlDslPackage getPackage()
  {
    return HtmlDslPackage.eINSTANCE;
  }

} //HtmlDslFactoryImpl
