/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl.validation;

import org.xtext.example.htmldsl.validation.AbstractHtmlDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class HtmlDslValidator extends AbstractHtmlDslValidator {
}
