=== Verhalten

[[behavior-paradigms]]
.Paradigmen zur Beschreibung des Verhaltens
image::mindmaps/behavior-paradigms/behavior-paradigms.svg[Paradigmen zur Beschreibung des Verhaltens, 100%]

* Concepts müssen nicht Abstractions eines wiederverwendeten Paradigmas nutzen: Wenn das Paradigma "State-based" verwendet wird, muss das Konzept, das als State fungiert, nicht unbedingt so genannt werden.

==== Imperative Programmierung

[[imperative]]
.Imperative Programmierung
image::mindmaps/behavior-paradigms/imperative.svg[Imperative Programmierung, 100%]

==== Funktionale Programmierung

[[functional]]
.Funktionale Programmierung
image::mindmaps/behavior-paradigms/functional.svg[Funktionale Programmierung, 100%]

==== Deklarative Programmierung

[[declarative]]
.Deklarative Programmierung
image::mindmaps/behavior-paradigms/declarative.svg[Deklarative Programmierung, 100%]

==== Eventbasierte Programmierung

[[event-based]]
.Eventbasierte Programmierung
image::mindmaps/behavior-paradigms/event-based.svg[Eventbasierte Programmierung, 100%]

==== Data Flow Programmierung

[[dataflow]]
.Data Flow Programmierung
image::mindmaps/behavior-paradigms/dataflow.svg[Data Flow Programmierung, 100%]

==== Automatenbasierte Programmierung

[[state-based]]
.Automatenbasierte Programmierung
image::mindmaps/behavior-paradigms/state-based.svg[Automatenbasierte Programmierung, 100%]

* Event-driven Mode: Ankommende Events triggern Transitionen und Aktionen.
* Timed Mode: Scheduler entscheidet, wann Event-Queues geprüft und verarbeitet werden.

==== Kombinationen

[[combination-paradigms]]
.Kombinationen verschiedener Paradigmen
image::mindmaps/combination-paradigms.svg[Kombinationen verschiedener Paradigmen, 100%]