/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.htmldsl.ui.internal.HtmldslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HtmlDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return HtmldslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HtmldslActivator.getInstance().getInjector(HtmldslActivator.ORG_XTEXT_EXAMPLE_HTMLDSL_HTMLDSL);
	}
	
}
