/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHtmlDslScopeProvider extends DelegatingScopeProvider {
}
