/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HtmlDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/htmldsl/parser/antlr/internal/InternalHtmlDsl.tokens");
	}
}
