/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.htmldsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.htmldsl.ui.internal.HtmldslActivator;

public class HtmlDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HtmldslActivator.getInstance().getInjector("org.xtext.example.htmldsl.HtmlDsl");
	}

}
