@startuml
!include Selector.plantuml
hide circle
hide empty methods
left to right direction
scale 3.25

abstract class Class {
    name : String
    selector : Selector
}

abstract class ContentClass {
    features : List<Feature>
}

abstract class PageClass {
    features : List<Feature>
}

abstract class ReferenceClass

abstract class Feature

Class <|-- ContentClass
Class <|-- PageClass
Class <|-- ReferenceClass
Class "0..n" --> "0..1" Selector : > is recognized by
ContentClass "1" --> "0..n" Feature : > specifies
PageClass "1" --> "0..n" Feature : > specifies
@enduml