@startuml
!include Selector.plantuml
hide circle
hide empty methods
skinparam linetype ortho
left to right direction
scale 3.25

abstract class Feature {
}

class Content<T extends ContentClass> {
    class : ContentClass = T
}

class Reference<T extends ReferenceClass> {
    class : ReferenceClass = T
}

abstract class ScalarFeature {
    name : String
    class : Class
    selector : Selector
}

class CollectionFeature<T extends ScalarFeature> {
    items : List<T>
}

ScalarFeature "0..n" <-- "0..1" CollectionFeature : < contains
Feature <|-- CollectionFeature
Feature <|-- ScalarFeature
ScalarFeature <|-- Content
ScalarFeature <|-- Reference
ScalarFeature "0..n" --> "0..1" Selector : > is recognized by
@enduml