@startuml
scale 3840*2160
hide circle
hide empty methods
skinparam linetype ortho

class Content {
    content : String
}

abstract class Feature {
    name : String
    class : String
    selector : Selector
}

abstract class FeatureCabable {
    contents : List<Content | List<Content>>
    references : List<Reference | List<Reference>>
}

class Page {
    url : String
    class : String
    status : String = "Classified"
}

class RangeSelector {
    type = "RangeSelector"
    startSelector : Selector
    endSelector : Selector
}

class Reference {
    destination : String
}

abstract class Selector {
    type : String
}

class XPathSelector {
    type = "XPathSelector"
    value : String
    offset : int
}

Content --|> FeatureCabable
Feature <|-- Content
Feature <|-- Reference
Feature "1" --> "1" Selector : > Has
FeatureCabable "1" --> "0..n" Content : > Has
Page --|> FeatureCabable
Reference "0..n" <-- "1" FeatureCabable : < Has
RangeSelector "0..n" --> "2" Selector : > Uses
Selector <|-- RangeSelector
Selector <|-- XPathSelector
@enduml